CONTIKI_PROJECT = Rime-Broadcast

CONTIKI_CONF_RANDOM_MAC=1
CONTIKI_WITH_RIME = 1

all: rime-broadcast.hex

# Root of the project repository
PROJECT_ROOT = ../../
include $(PROJECT_ROOT)/Makefile.include
